<?xml version="1.0"?>
<!DOCTYPE DtdList [
<!ELEMENT DtdList (Dtd+)>
<!ELEMENT Dtd (Descriptor, Text, doctype*, depends*)>
<!ATTLIST Dtd filename CDATA #REQUIRED>
<!ELEMENT Descriptor (#PCDATA)>
<!ATTLIST Descriptor 
    language CDATA "EN"
    organization CDATA "Tufts HSDB"
>
<!ELEMENT Text (#PCDATA)>
<!ELEMENT doctype (#PCDATA)>
<!ELEMENT depends EMPTY>
<!ATTLIST depends dependency (prereq|includes) "includes">
<!ATTLIST depends filename CDATA #REQUIRED>
]>
<?xml-stylesheet href="dtdlist.xsl" type="text/xsl"?>
<DtdList>
  <Dtd filename="hscml.dtd">
    <Descriptor>DTD Syllabus document</Descriptor>
    <Text>Contains information for describing a syllabus document, and
    all of the associated content of it, especially for structuring
    text and marking it up semantically.</Text>
    <doctype>content</doctype>
    <depends filename="entities.dtd"/>
    <depends filename="XMLlat1.ent"/>
    <depends filename="XMLsymbol.ent"/>
    <depends filename="XMLspecial.ent"/>
    <depends filename="inline.dtd"/>
    <depends filename="person.dtd"/>
    <depends filename="biblio.dtd"/>
    <depends filename="header.dtd"/>
    <depends filename="structure.dtd"/>
  </Dtd>

  <Dtd filename="dbcontent.dtd">
    <Descriptor>DTD Syllabus document (internal)</Descriptor>
    <Text>Contains information for describing a syllabus document, but
    with database-stored header information stripped out.</Text>
    <doctype>db-content</doctype>
    <depends filename="entities.dtd"/>
    <depends filename="XMLlat1.ent"/>
    <depends filename="XMLsymbol.ent"/>
    <depends filename="XMLspecial.ent"/>
    <depends filename="inline.dtd"/>
    <depends filename="person.dtd"/>
    <depends filename="biblio.dtd"/>
    <depends filename="header.dtd"/>
    <depends filename="structure.dtd"/>
    <depends filename="asscoiated_data.dtd"/>
  </Dtd>

  <Dtd filename="question.dtd">
    <Descriptor>DTD Quiz description</Descriptor>
    <Text>Format for entering many teaching questions of various
    types.</Text>
    <doctype>question-block</doctype>
    <depends filename="entities.dtd"/>
    <depends filename="inline.dtd"/>
    <depends filename="header.dtd"/>
  </Dtd>

  <Dtd filename="slide.dtd">
    <Descriptor>DTD Image description</Descriptor>
    <Text>Description of an educational image, include header metadata
    and associated data.</Text>
    <doctype>content-slide</doctype>
    <depends filename="entities.dtd"/>
    <depends filename="XMLlat1.ent"/>
    <depends filename="XMLsymbol.ent"/>
    <depends filename="XMLspecial.ent"/>
    <depends filename="inline.dtd"/>
    <depends filename="person.dtd"/>
    <depends filename="biblio.dtd"/>
    <depends filename="header.dtd"/>
    <depends filename="structure.dtd"/>
    <depends filename="binary_data.dtd"/>
  </Dtd>

  <Dtd filename="course.dtd">
    <Descriptor>DTD Course description</Descriptor>
    <Text>Format for descriptions of a HSDB course, include
    information on its title, faculty list, assignments, etc.</Text>
    <doctype>course</doctype>
    <depends filename="entities.dtd"/>
    <depends filename="XMLlat1.ent"/>
    <depends filename="XMLsymbol.ent"/>
    <depends filename="XMLspecial.ent"/>
    <depends filename="inline.dtd"/>
    <depends filename="person.dtd"/>
    <depends filename="biblio.dtd"/>
  </Dtd>

  <Dtd filename="eval.dtd">
    <Descriptor>DTD Course evaluation form</Descriptor>
    <Text>Outlines the form for an eval, with all its associated
    question types and information.</Text>
    <doctype>Eval</doctype>
    <depends filename="entities.dtd"/>
    <depends filename="XMLlat1.ent"/>
    <depends filename="XMLsymbol.ent"/>
    <depends filename="XMLspecial.ent"/>
    <depends filename="inline.dtd"/>
    <depends filename="structure.dtd"/>
  </Dtd>

  <Dtd filename="Eval_Results.dtd">
    <Descriptor>DTD Course evaluation results</Descriptor>
    <Text>Format for the results of an eval, including
    complete/incomplete users and response statistics.</Text>
    <doctype>Eval_Results</doctype>
    <depends filename="eval.dtd"/>
  </Dtd>

  <Dtd filename="teaching_site.dtd">
    <Descriptor>DTD Teaching site description</Descriptor>
    <Text>Textual information about a teaching site, such as a
    description, and various contact information, directions, URL,
    etc.</Text>
    <doctype>TeachingSite</doctype>
    <doctype>TeachingSiteList</doctype>
    <depends filename="entities.dtd"/>
    <depends filename="XMLlat1.ent"/>
    <depends filename="XMLsymbol.ent"/>
    <depends filename="XMLspecial.ent"/>
    <depends filename="inline.dtd"/>
    <depends filename="structure.dtd"/>
  </Dtd>

  <Dtd filename="inline.dtd">
    <Descriptor>DTD Text Elements</Descriptor>
    <Text>Contains information for the markup of elements with the
    context of a paragraph-like structure. Used in many HSDB-related
    DTD's. No doctypes, but "Inline" and "Limited-Inline" parameter
    entities are frequently used.</Text>
    <depends dependency="prereq" filename="entities.dtd"/>
  </Dtd>

  <Dtd filename="structure.dtd">
    <Descriptor>DTD Structural elements</Descriptor>
    <Text>Description of the various structures for a structured
    document. No doctypes, but "Flow" and "Block" parameter entities
    are frequently used.</Text>
    <depends dependency="prereq" filename="inline.dtd"/>
  </Dtd>

  <Dtd filename="header.dtd">
    <Descriptor>DTD Header metadata</Descriptor>
    <Text>Description of the metadata associated with a document in
    the HSDB system.</Text>
    <depends dependency="prereq" filename="person.dtd"/>
    <depends dependency="prereq" filename="inline.dtd"/>
  </Dtd>

  <Dtd filename="person.dtd">
    <Descriptor>DTD Users and other people</Descriptor>
    <Text>Descriptions of users (active registered users of the HSDB
    system) and other people who aren't part of that system.</Text>
    <doctype>user</doctype>
    <doctype>non-user</doctype>
  </Dtd>

  <Dtd filename="biblio.dtd">
    <Descriptor>DTD Bibliographic info</Descriptor>
    <Text>Descriptions of references for citation purposes.</Text>
    <doctype>bibliography</doctype>
    <depends dependency="prereq" filename="inline.dtd"/>
  </Dtd>

  <Dtd filename="associated_data.dtd">
    <Descriptor>DTD More HSDB meta-data</Descriptor>
    <Text>Stores meta data associated with HSDB content that's not
    stored in the database.</Text>
    <doctype>associated-data</doctype>
  </Dtd>

  <Dtd filename="binary_data.dtd">
    <Descriptor>DTD Binary data description</Descriptor>
    <Text>Describes a binary data object in HSDB.</Text>
    <doctype>binary-data</doctype>
  </Dtd>

  <Dtd filename="entities.dtd">
    <Descriptor>DTD Utitlity entities</Descriptor>
    <Text>Defines commonly used entities for other DTDs.</Text>
  </Dtd>

  <Dtd filename="XMLlat1.ent">
    <Descriptor>ENTITIES Latin 1 for XHTML</Descriptor>
    <Text>Entity list for the Latin 1 character set
    (ISO-8859-1). Based on the standard from W3C, but modified for
    HSDB purposes.</Text>
  </Dtd>

  <Dtd filename="XMLsymbol.ent">
    <Descriptor>ENTITIES Symbols for XHTML</Descriptor>
    <Text>Entity list for symbols (arrows, Greek characters). Based on
    the standard from W3C, but modified for HSDB purposes.</Text>
  </Dtd>

  <Dtd filename="XMLspecial.ent">
    <Descriptor>ENTITIES Special for XHTML</Descriptor>
    <Text>Entity list for special typographical markup (quotation
    marks, special spaces, etc.).</Text>
  </Dtd>
</DtdList>

<!--
Local Variables:
mode: xml
sgml-set-face: t
sgml-indent-step: 2
sgml-indent-data: t
sgml-auto-activate-dtd: t
sgml-live-element-indicator: t
End:
-->