<!--
 Copyright 2012 Tufts University 

 Licensed under the Educational Community License, Version 1.0 (the "License"); 
 you may not use this file except in compliance with the License. 
 You may obtain a copy of the License at 

 http://www.opensource.org/licenses/ecl1.php 

 Unless required by applicable law or agreed to in writing, software 
 distributed under the License is distributed on an "AS IS" BASIS, 
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
 See the License for the specific language governing permissions and 
 limitations under the License.
-->


<?xml version="1.0" standalone="yes"?>
<!-- 
   Database of glyphs and some of their properties.  Needed to
   generate various HSDB stuff.
   Tarik Alkasab <tarik.alkasab@neurosci.tufts.edu>
   $Revision: 1.4 $
   $Date: 2012-04-20 16:52:32 $ 
-->
<!DOCTYPE glyph-set [
  <!ELEMENT glyph-set ((glyph-set|glyph)+)>
  <!ATTLIST glyph-set 
          name CDATA #REQUIRED>
  <!ELEMENT glyph (name, render-by, glyph-image, comment?)>
  <!ATTLIST glyph 
          code CDATA #REQUIRED>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT render-by EMPTY>
  <!ATTLIST render-by 
          method (name|number|image) "image">
  <!ELEMENT glyph-image EMPTY>
  <!ATTLIST glyph-image 
	  height CDATA #REQUIRED
	  width CDATA #REQUIRED
	  src CDATA #REQUIRED>
  <!ELEMENT comment (#PCDATA)>
]>

<glyph-set name="all">
  <glyph-set name="latin1">
    <glyph code="00A0">
      <name>nbsp</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00A0.png"
		   width="19"/>
      <comment></comment>
    </glyph>

    <glyph code="00A1">
      <name>iexcl</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00A1.png"
      width="6"/>
      <comment></comment>
    </glyph>

    <glyph code="00A2">
      <name>cent</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00A2.png"
      width="10"/>
      <comment></comment>
    </glyph>

    <glyph code="00A3">
      <name>pound</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00A3.png"
      width="10"/>
      <comment></comment>
    </glyph>

    <glyph code="00A4">
      <name>curren</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00A4.png"
      width="10"/>
      <comment></comment>
    </glyph>

    <glyph code="00A5">
      <name>yen</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00A5.png"
      width="10"/>
      <comment></comment>
    </glyph>

    <glyph code="00A6">
      <name>brvbar</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00A6.png"
      width="4"/>
      <comment></comment>
    </glyph>

    <glyph code="00A7">
      <name>sect</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00A7.png"
      width="10"/>
      <comment></comment>
    </glyph>

    <glyph code="00A8">
      <name>uml</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00A8.png"
      width="6"/>
      <comment></comment>
    </glyph>

    <glyph code="00A9">
      <name>copy</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00A9.png"
      width="14"/>
      <comment></comment>
    </glyph>

    <glyph code="00AA">
      <name>ordf</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00AA.png"
      width="5"/>
      <comment></comment>
    </glyph>

    <glyph code="00AB">
      <name>laquo</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00AB.png"
      width="10"/>
      <comment></comment>
    </glyph>

    <glyph code="00AC">
      <name>not</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00AC.png"
      width="11"/>
      <comment></comment>
    </glyph>

    <glyph code="00AD">
      <name>shy</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00AD.png"
      width="6"/>
      <comment></comment>
    </glyph>

    <glyph code="00AE">
      <name>reg</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00AE.png"
      width="14"/>
      <comment></comment>
    </glyph>

    <glyph code="00AF">
      <name>macr</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00AF.png"
      width="10"/>
      <comment></comment>
    </glyph>

    <glyph code="00B0">
      <name>deg</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00B0.png"
      width="8"/>
      <comment></comment>
    </glyph>

    <glyph code="00B1">
      <name>plusmn</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00B1.png"
      width="10"/>
      <comment></comment>
    </glyph>

    <glyph code="00B2">
      <name>sup2</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00B2.png"
      width="6"/>
      <comment></comment>
    </glyph>

    <glyph code="00B3">
      <name>sup3</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00B3.png"
      width="6"/>
      <comment></comment>
    </glyph>

    <glyph code="00B4">
      <name>acute</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00B4.png"
      width="6"/>
      <comment></comment>
    </glyph>

    <glyph code="00B5">
      <name>micro</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00B5.png"
      width="11"/>
      <comment></comment>
    </glyph>

    <glyph code="00B6">
      <name>para</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00B6.png"
      width="9"/>
      <comment></comment>
    </glyph>

    <glyph code="00B7">
      <name>middot</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00B7.png"
      width="5"/>
      <comment></comment>
    </glyph>

    <glyph code="00B8">
      <name>cedil</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00B8.png"
      width="6"/>
      <comment></comment>
    </glyph>

    <glyph code="00B9">
      <name>sup1</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00B9.png"
      width="6"/>
      <comment></comment>
    </glyph>

    <glyph code="00BA">
      <name>ordm</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00BA.png"
      width="6"/>
      <comment></comment>
    </glyph>

    <glyph code="00BB">
      <name>raquo</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00BB.png"
      width="10"/>
      <comment></comment>
    </glyph>

    <glyph code="00BC">
      <name>frac14</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00BC.png"
      width="14"/>
      <comment></comment>
    </glyph>

    <glyph code="00BD">
      <name>frac12</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00BD.png"
      width="14"/>
      <comment></comment>
    </glyph>

    <glyph code="00BE">
      <name>frac34</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00BE.png"
      width="14"/>
      <comment></comment>
    </glyph>

    <glyph code="00BF">
      <name>iquest</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00BF.png"
      width="8"/>
      <comment></comment>
    </glyph>

    <glyph code="00C0">
      <name>Agrave</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00C0.png"
      width="13"/>
      <comment></comment>
    </glyph>

    <glyph code="00C1">
      <name>Aacute</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00C1.png"
      width="13"/>
      <comment></comment>
    </glyph>

    <glyph code="00C2">
      <name>Acirc</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00C2.png"
      width="13"/>
      <comment></comment>
    </glyph>

    <glyph code="00C3">
      <name>Atilde</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00C3.png"
      width="13"/>
      <comment></comment>
    </glyph>

    <glyph code="00C4">
      <name>Auml</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00C4.png"
      width="13"/>
      <comment></comment>
    </glyph>

    <glyph code="00C5">
      <name>Aring</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00C5.png"
      width="13"/>
      <comment></comment>
    </glyph>

    <glyph code="00C6">
      <name>AElig</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00C6.png"
      width="17"/>
      <comment></comment>
    </glyph>

    <glyph code="00C7">
      <name>Ccedil</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00C7.png"
      width="13"/>
      <comment></comment>
    </glyph>

    <glyph code="00C8">
      <name>Egrave</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00C8.png"
      width="11"/>
      <comment></comment>
    </glyph>

    <glyph code="00C9">
      <name>Eacute</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00C9.png"
      width="11"/>
      <comment></comment>
    </glyph>

    <glyph code="00CA">
      <name>Ecirc</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00CA.png"
      width="11"/>
      <comment></comment>
    </glyph>

    <glyph code="00CB">
      <name>Euml</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00CB.png"
      width="11"/>
      <comment></comment>
    </glyph>

    <glyph code="00CC">
      <name>Igrave</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00CC.png"
      width="6"/>
      <comment></comment>
    </glyph>

    <glyph code="00CD">
      <name>Iacute</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00CD.png"
      width="6"/>
      <comment></comment>
    </glyph>

    <glyph code="00CE">
      <name>Icirc</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00CE.png"
      width="6"/>
      <comment></comment>
    </glyph>

    <glyph code="00CF">
      <name>Iuml</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00CF.png"
      width="6"/>
      <comment></comment>
    </glyph>

    <glyph code="00D0">
      <name>ETH</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00D0.png"
      width="13"/>
      <comment></comment>
    </glyph>

    <glyph code="00D1">
      <name>Ntilde</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00D1.png"
      width="13"/>
      <comment></comment>
    </glyph>

    <glyph code="00D2">
      <name>Ograve</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00D2.png"
      width="13"/>
      <comment></comment>
    </glyph>

    <glyph code="00D3">
      <name>Oacute</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00D3.png"
      width="13"/>
      <comment></comment>
    </glyph>

    <glyph code="00D4">
      <name>Ocirc</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00D4.png"
      width="13"/>
      <comment></comment>
    </glyph>

    <glyph code="00D5">
      <name>Otilde</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00D5.png"
      width="13"/>
      <comment></comment>
    </glyph>

    <glyph code="00D6">
      <name>Ouml</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00D6.png"
      width="13"/>
      <comment></comment>
    </glyph>

    <glyph code="00D7">
      <name>times</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00D7.png"
      width="11"/>
      <comment></comment>
    </glyph>

    <glyph code="00D8">
      <name>Oslash</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00D8.png"
      width="13"/>
      <comment></comment>
    </glyph>

    <glyph code="00D9">
      <name>Ugrave</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00D9.png"
      width="13"/>
      <comment></comment>
    </glyph>

    <glyph code="00DA">
      <name>Uacute</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00DA.png"
      width="13"/>
      <comment></comment>
    </glyph>

    <glyph code="00DB">
      <name>Ucirc</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00DB.png"
      width="13"/>
      <comment></comment>
    </glyph>

    <glyph code="00DC">
      <name>Uuml</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00DC.png"
      width="13"/>
      <comment></comment>
    </glyph>

    <glyph code="00DD">
      <name>Yacute</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00DD.png"
      width="13"/>
      <comment></comment>
    </glyph>

    <glyph code="00DE">
      <name>THORN</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00DE.png"
      width="11"/>
      <comment></comment>
    </glyph>

    <glyph code="00DF">
      <name>szlig</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00DF.png"
      width="10"/>
      <comment></comment>
    </glyph>

    <glyph code="00E0">
      <name>agrave</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00E0.png"
      width="8"/>
      <comment></comment>
    </glyph>

    <glyph code="00E1">
      <name>aacute</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00E1.png"
      width="8"/>
      <comment></comment>
    </glyph>

    <glyph code="00E2">
      <name>acirc</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00E2.png"
      width="8"/>
      <comment></comment>
    </glyph>

    <glyph code="00E3">
      <name>atilde</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00E3.png"
      width="8"/>
      <comment></comment>
    </glyph>

    <glyph code="00E4">
      <name>auml</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00E4.png"
      width="8"/>
      <comment></comment>
    </glyph>

    <glyph code="00E5">
      <name>aring</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00E5.png"
      width="8"/>
      <comment></comment>
    </glyph>

    <glyph code="00E6">
      <name>aelig</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00E6.png"
      width="13"/>
      <comment></comment>
    </glyph>

    <glyph code="00E7">
      <name>ccedil</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00E7.png"
      width="8"/>
      <comment></comment>
    </glyph>

    <glyph code="00E8">
      <name>egrave</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00E8.png"
      width="8"/>
      <comment></comment>
    </glyph>

    <glyph code="00E9">
      <name>eacute</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00E9.png"
      width="8"/>
      <comment></comment>
    </glyph>

    <glyph code="00EA">
      <name>ecirc</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00EA.png"
      width="8"/>
      <comment></comment>
    </glyph>

    <glyph code="00EB">
      <name>euml</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00EB.png"
      width="8"/>
      <comment></comment>
    </glyph>

    <glyph code="00EC">
      <name>igrave</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00EC.png"
      width="6"/>
      <comment></comment>
    </glyph>

    <glyph code="00ED">
      <name>iacute</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00ED.png"
      width="6"/>
      <comment></comment>
    </glyph>

    <glyph code="00EE">
      <name>icirc</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00EE.png"
      width="6"/>
      <comment></comment>
    </glyph>

    <glyph code="00EF">
      <name>iuml</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00EF.png"
      width="6"/>
      <comment></comment>
    </glyph>

    <glyph code="00F0">
      <name>eth</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00F0.png"
      width="10"/>
      <comment></comment>
    </glyph>

    <glyph code="00F1">
      <name>ntilde</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00F1.png"
      width="10"/>
      <comment></comment>
    </glyph>

    <glyph code="00F2">
      <name>ograve</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00F2.png"
      width="10"/>
      <comment></comment>
    </glyph>

    <glyph code="00F3">
      <name>oacute</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00F3.png"
      width="10"/>
      <comment></comment>
    </glyph>

    <glyph code="00F4">
      <name>ocirc</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00F4.png"
      width="10"/>
      <comment></comment>
    </glyph>

    <glyph code="00F5">
      <name>otilde</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00F5.png"
      width="10"/>
      <comment></comment>
    </glyph>

    <glyph code="00F6">
      <name>ouml</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00F6.png"
      width="10"/>
      <comment></comment>
    </glyph>

    <glyph code="00F7">
      <name>divide</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00F7.png"
      width="10"/>
      <comment></comment>
    </glyph>

    <glyph code="00F8">
      <name>oslash</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00F8.png"
      width="10"/>
      <comment></comment>
    </glyph>

    <glyph code="00F9">
      <name>ugrave</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00F9.png"
      width="10"/>
      <comment></comment>
    </glyph>

    <glyph code="00FA">
      <name>uacute</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00FA.png"
      width="10"/>
      <comment></comment>
    </glyph>

    <glyph code="00FB">
      <name>ucirc</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00FB.png"
      width="10"/>
      <comment></comment>
    </glyph>

    <glyph code="00FC">
      <name>uuml</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00FC.png"
      width="10"/>
      <comment></comment>
    </glyph>

    <glyph code="00FD">
      <name>yacute</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00FD.png"
      width="10"/>
      <comment></comment>
    </glyph>

    <glyph code="00FE">
      <name>thorn</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00FE.png"
      width="10"/>
      <comment></comment>
    </glyph>

    <glyph code="00FF">
      <name>yuml</name>
      <render-by method="name"/>
      <glyph-image height="20" src="/icons/glyphs/U00FF.png"
      width="10"/>
      <comment></comment>
    </glyph>
  </glyph-set>

  <glyph-set name="special">
    <glyph code="0152">
      <name>OElig</name>
      <render-by method="image"/>
      <glyph-image height="20" src="/icons/glyphs/U0152.png"
      width="17"/>
      <comment></comment>
    </glyph>

    <glyph code="0153">
      <name>oelig</name>
      <render-by method="image"/>
      <glyph-image height="20" src="/icons/glyphs/U0153.png"
      width="13"/>
      <comment></comment>
    </glyph>

    <glyph code="0160">
      <name>Scaron</name>
      <render-by method="image"/>
      <glyph-image height="20" src="/icons/glyphs/U0160.png"
      width="11"/>
      <comment></comment>
    </glyph>

    <glyph code="0161">
      <name>scaron</name>
      <render-by method="image"/>
      <glyph-image height="20" src="/icons/glyphs/U0161.png"
      width="8"/>
      <comment></comment>
    </glyph>

    <glyph code="0178">
      <name>Yuml</name>
      <render-by method="image"/>
      <glyph-image height="20" src="/icons/glyphs/U0178.png"
      width="13"/>
      <comment></comment>
    </glyph>

    <glyph code="02C6">
      <name>circ</name>
      <render-by method="image"/>
      <glyph-image height="20" src="/icons/glyphs/U02C6.png"
      width="6"/>
      <comment></comment>
    </glyph>

    <glyph code="02DC">
      <name>tilde</name>
      <render-by method="image"/>
      <glyph-image height="20" src="/icons/glyphs/U02DC.png"
      width="6"/>
      <comment></comment>
    </glyph>

    <glyph code="2002">
      <name>ensp</name>
      <render-by method="image"/>
      <glyph-image height="20" src="/icons/glyphs/U2002.png"
      width="19"/>
      <comment></comment>
    </glyph>

    <glyph code="2003">
      <name>emsp</name>
      <render-by method="image"/>
      <glyph-image height="20" src="/icons/glyphs/U2003.png"
      width="19"/>
      <comment></comment>
    </glyph>

    <glyph code="2009">
      <name>thinsp</name>
      <render-by method="image"/>
      <glyph-image height="20" src="/icons/glyphs/U2009.png"
      width="19"/>
      <comment></comment>
    </glyph>

    <glyph code="200C">
      <name>zwnj</name>
      <render-by method="image"/>
      <glyph-image height="20" src="/icons/glyphs/U200C.png"
      width="19"/>
      <comment></comment>
    </glyph>

    <glyph code="200D">
      <name>zwj</name>
      <render-by method="image"/>
      <glyph-image height="20" src="/icons/glyphs/U200D.png"
      width="19"/>
      <comment></comment>
    </glyph>

    <glyph code="200E">
      <name>lrm</name>
      <render-by method="image"/>
      <glyph-image height="20" src="/icons/glyphs/U200E.png"
      width="19"/>
      <comment></comment>
    </glyph>

    <glyph code="200F">
      <name>rlm</name>
      <render-by method="image"/>
      <glyph-image height="20" src="/icons/glyphs/U200F.png"
      width="19"/>
      <comment></comment>
    </glyph>

    <glyph code="2013">
      <name>ndash</name>
      <render-by method="image"/>
      <glyph-image height="20" src="/icons/glyphs/U2013.png"
      width="10"/>
      <comment></comment>
    </glyph>

    <glyph code="2014">
      <name>mdash</name>
      <render-by method="image"/>
      <glyph-image height="20" src="/icons/glyphs/U2014.png"
      width="19"/>
      <comment></comment>
    </glyph>

    <glyph code="2018">
      <name>lsquo</name>
      <render-by method="image"/>
      <glyph-image height="20" src="/icons/glyphs/U2018.png"
      width="6"/>
      <comment></comment>
    </glyph>

    <glyph code="2019">
      <name>rsquo</name>
      <render-by method="image"/>
      <glyph-image height="20" src="/icons/glyphs/U2019.png"
      width="6"/>
      <comment></comment>
    </glyph>

    <glyph code="201A">
      <name>sbquo</name>
      <render-by method="image"/>
      <glyph-image height="20" src="/icons/glyphs/U201A.png"
      width="6"/>
      <comment></comment>
    </glyph>

    <glyph code="201C">
      <name>ldquo</name>
      <render-by method="image"/>
      <glyph-image height="20" src="/icons/glyphs/U201C.png"
      width="8"/>
      <comment></comment>
    </glyph>

    <glyph code="201D">
      <name>rdquo</name>
      <render-by method="image"/>
      <glyph-image height="20" src="/icons/glyphs/U201D.png"
      width="8"/>
      <comment></comment>
    </glyph>

    <glyph code="201E">
      <name>bdquo</name>
      <render-by method="image"/>
      <glyph-image height="20" src="/icons/glyphs/U201E.png"
      width="8"/>
      <comment></comment>
    </glyph>

    <glyph code="2020">
      <name>dagger</name>
      <render-by method="image"/>
      <glyph-image height="20" src="/icons/glyphs/U2020.png"
      width="10"/>
      <comment></comment>
    </glyph>

    <glyph code="2021">
      <name>Dagger</name>
      <render-by method="image"/>
      <glyph-image height="20" src="/icons/glyphs/U2021.png"
      width="10"/>
      <comment></comment>
    </glyph>

    <glyph code="2030">
      <name>permil</name>
      <render-by method="image"/>
      <glyph-image height="20" src="/icons/glyphs/U2030.png"
      width="21"/>
      <comment></comment>
    </glyph>

    <glyph code="2039">
      <name>lsaquo</name>
      <render-by method="image"/>
      <glyph-image height="20" src="/icons/glyphs/U2039.png"
      width="6"/>
      <comment></comment>
    </glyph>

    <glyph code="203A">
      <name>rsaquo</name>
      <render-by method="image"/>
      <glyph-image height="20" src="/icons/glyphs/U203A.png"
      width="6"/>
      <comment></comment>
    </glyph>

    <glyph code="20AC">
      <name>euro</name>
      <render-by method="image"/>
      <glyph-image height="20" src="/icons/glyphs/U20AC.png"
      width="10"/>
      <comment></comment>
    </glyph>
  </glyph-set>

  <glyph-set name="symbol">
    <glyph code="0192">
      <name>fnof</name>
      <render-by method="image"/>
      <glyph-image height="20" width="6"
      src="/icons/glyphs/U0192.png"/>
      <comment>latin small f with hook = function</comment>
    </glyph>
	

    <glyph code="0391">
      <name>Alpha</name>
      <render-by method="image"/>
      <glyph-image height="20" src="/icons/glyphs/U0391.png"
      width="13"/>
      <comment></comment>
    </glyph>

    <glyph code="0392">
      <name>Beta</name>
      <render-by method="image"/>
      <glyph-image height="20" src="/icons/glyphs/U0392.png"
      width="13"/>
      <comment></comment>
    </glyph>

    <glyph code="0393">
      <name>Gamma</name>
      <render-by method="image"/>
      <glyph-image height="20" src="/icons/glyphs/U0393.png"
      width="11"/>
      <comment></comment>
    </glyph>

    <glyph code="0394">
      <name>Delta</name>
      <render-by method="image"/>
      <glyph-image height="20" src="/icons/glyphs/U0394.png"
      width="12"/>
      <comment></comment>
    </glyph>

    <glyph code="0395">
      <name>Epsilon</name>
      <render-by method="image"/>
      <glyph-image height="20" src="/icons/glyphs/U0395.png"
      width="11"/>
      <comment></comment>
    </glyph>

    <glyph code="0396">
      <name>Zeta</name>
      <render-by method="image"/>
      <glyph-image height="20" src="/icons/glyphs/U0396.png"
      width="11"/>
      <comment></comment>
    </glyph>

    <glyph code="0397">
      <name>Eta</name>
      <render-by method="image"/>
      <glyph-image height="20" src="/icons/glyphs/U0397.png"
      width="13"/>
      <comment></comment>
    </glyph>

    <glyph code="0398">
      <name>Theta</name>
      <render-by method="image"/>
      <glyph-image height="20" src="/icons/glyphs/U0398.png"
      width="13"/>
      <comment></comment>
    </glyph>

    <glyph code="0399">
      <name>Iota</name>
      <render-by method="image"/>
      <glyph-image height="20" src="/icons/glyphs/U0399.png"
      width="6"/>
      <comment></comment>
    </glyph>

    <glyph code="039A">
      <name>Kappa</name>
      <render-by method="image"/>
      <glyph-image height="20" src="/icons/glyphs/U039A.png"
      width="13"/>
      <comment></comment>
    </glyph>

    <glyph code="039B">
      <name>Lambda</name>
      <render-by method="image"/>
      <glyph-image height="20" src="/icons/glyphs/U039B.png"
      width="13"/>
      <comment></comment>
    </glyph>

    <glyph code="039C">
      <name>Mu</name>
      <render-by method="image"/>
      <glyph-image height="20" src="/icons/glyphs/U039C.png"
      width="17"/>
      <comment></comment>
    </glyph>

    <glyph code="039D">
      <name>Nu</name>
      <render-by method="image"/>
      <glyph-image height="20" src="/icons/glyphs/U039D.png"
      width="13"/>
      <comment></comment>
    </glyph>

    <glyph code="039E">
      <name>Xi</name>
      <render-by method="image"/>
      <glyph-image height="20" src="/icons/glyphs/U039E.png"
      width="13"/>
      <comment></comment>
    </glyph>

    <glyph code="039F">
      <name>Omicron</name>
      <render-by method="image"/>
      <glyph-image height="20" src="/icons/glyphs/U039F.png"
      width="13"/>
      <comment></comment>
    </glyph>

    <glyph code="03A0">
      <name>Pi</name>
      <render-by method="image"/>
      <glyph-image height="20" src="/icons/glyphs/U03A0.png"
      width="13"/>
      <comment></comment>